name: Build
on: push

env:
  # shared paths for all builds
  TOOLS_PATH: ${{ github.workspace }}/tools
  INSTALL_PATH: ${{ github.workspace }}/install
  PKG_CONFIG_PATH: ${{ github.workspace }}/install/lib/pkgconfig
  INCLUDE: ${{ github.workspace }}/install/include
  LIBPATH: ${{ github.workspace }}/install/lib
  LINK: "/LIBPATH:${{ github.workspace }}/install/lib"
  # tools: pkg-config, win_flex_bison
  PKG_CONFIG_RELEASE: https://nirbheek.in/files/binaries/pkg-config/win32/pkg-config.exe
  WIN_FLEX_BISON_RELEASE: https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip
  CARGO_CBUILD_RELEASE: https://github.com/lu-zero/cargo-c/releases/download/v0.10.5/cargo-c-windows-msvc.zip
  # libraries to build
  FREETYPE2_RELEASE: https://download.savannah.gnu.org/releases/freetype/freetype-2.13.3.tar.xz
  FREETYPE2: freetype-2.13.3
  LIBXML2_RELEASE: https://download.gnome.org/sources/libxml2/2.13/libxml2-2.13.4.tar.xz
  LIBXML2: libxml2-2.13.4
  LIBRSVG_RELEASE: https://download.gnome.org/sources/librsvg/2.58/librsvg-2.58.5.tar.xz
  LIBRSVG: librsvg-2.58.5
  GTK_RELEASE: https://download.gnome.org/sources/gtk/4.15/gtk-4.15.6.tar.xz
  GTK: gtk-4.15.6
  LIBADWAITA_RELEASE: https://download.gnome.org/sources/libadwaita/1.5/libadwaita-1.6.1.tar.xz
  LIBADWAITA: libadwaita-1.6.1

jobs:
  build:
    name: Build GNOME Stack
    runs-on: windows-latest
    steps:
    # tools setup: meson, pkg-config, win_flex_bison, MSVC
    - name: Setup Meson latest
      run: pip install --upgrade meson ninja
    - name: Setup pkg-config
      run: |
        mkdir tools
        curl "$env:PKG_CONFIG_RELEASE" -o tools/pkg-config.exe
        echo "$env:TOOLS_PATH" >> $env:GITHUB_PATH
        echo "$env:INSTALL_PATH/bin" >> $env:GITHUB_PATH
    - name: Setup win_flex_bison
      run: |
        curl -L "$env:WIN_FLEX_BISON_RELEASE" -o tools/win_flex_bison.zip
        python -m zipfile -e tools/win_flex_bison.zip tools/win_flex_bison
        echo "$env:TOOLS_PATH/win_flex_bison" >> $env:GITHUB_PATH
    - name: Prepare MSVC
      uses: ilammy/msvc-dev-cmd@v1
    # librsvg expects MSVC-flavoured Rust
    - name: Setup Rust Toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Setup cargo-cbuild
      run: |
        curl -L "$env:CARGO_CBUILD_RELEASE" -o tools/cargo-c.zip
        python -m zipfile -e tools/cargo-c.zip tools/cargo-c
        echo "$env:TOOLS_PATH/cargo-c" >> $env:GITHUB_PATH
    # build GTK bundle
    - name: Fetch and Build GTK
      run: |
        curl -L -O "$env:GTK_RELEASE"
        cmake -E tar xf "$env:GTK.tar.xz"
        cd "$env:GTK"
        meson setup builddir --prefix="$env:INSTALL_PATH" --buildtype=release -Dbuild-tests=false -Dmedia-gstreamer=disabled -Dvulkan=disabled
        meson install -C builddir
    # build librsvg
    # .. build freetype2
    - name: Fetch and Build freetype2
      run: |
        curl -L -O "$env:FREETYPE2_RELEASE"
        cmake -E tar xf "$env:FREETYPE2.tar.xz"
        cd "$env:FREETYPE2"
        meson setup builddir --prefix="$env:INSTALL_PATH" --buildtype=release
        meson install -C builddir
    # .. build libxml2
    - name: Fetch and Build libxml2
      run: |
        curl -L -O "$env:LIBXML2_RELEASE"
        cmake -E tar xf "$env:LIBXML2.tar.xz"
        cmake -S "$env:LIBXML2" -B "$env:LIBXML2/build" -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="$env:INSTALL_PATH" -DLIBXML2_WITH_ICONV=OFF -DLIBXML2_WITH_LZMA=OFF -DLIBXML2_WITH_PYTHON=OFF -DLIBXML2_WITH_ZLIB=OFF
        cmake --build "$env:LIBXML2/build" --config Release
        cmake --install "$env:LIBXML2/build"
        cp "$env:INSTALL_PATH/lib/libxml2s.lib" "$env:INSTALL_PATH/lib/libxml2.lib"
        cp "$env:INSTALL_PATH/lib/libxml2s.lib" "$env:INSTALL_PATH/lib/xml2.lib"
    # .. build librsvg
    - name: Fetch and Build librsvg
      run: |
        curl -L -O "$env:LIBRSVG_RELEASE"
        cmake -E tar xf "$env:LIBRSVG.tar.xz"
        cd "$env:LIBRSVG/win32"
        nmake /f Makefile.vc install CFG=release PREFIX="$env:INSTALL_PATH" RUSTUP=rustup CARGO=cargo
    # build libadwaita
    - name: Fetch and Build libadwaita
      run: |
        curl -L -O "$env:LIBADWAITA_RELEASE"
        cmake -E tar xf "$env:LIBADWAITA.tar.xz"
        cd "$env:LIBADWAITA"
        meson setup builddir --prefix="$env:INSTALL_PATH" --buildtype=release -Dvapi=false
        meson install -C builddir
    # finish build and upload artifact
    - uses: actions/upload-artifact@v3
      with:
        name: gtk-msvc-release
        path: ${{ env.INSTALL_PATH }}
